<a href="https://colab.research.google.com/github/Maryam-Yaqoob/ANN-LAB/blob/main/FA23_BAI_025___Lab_2___Maryam_Yaqoob.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 02 – NumPy for ANN

In [1]:
import numpy as np

## Task 1: Vectors

In [2]:
ages = np.array([22, 35, 41, 28, 53, 60])
print("Ages:", ages)
print("Shape:", ages.shape)
print("Dimensions:", ages.ndim)
print("Data type:", ages.dtype)

# Years until retirement (vectorised, no loop)
years_to_retirement = 65 - ages
print("Years until retirement:", years_to_retirement)

# Average age using a NumPy function
print("Average age:", np.mean(ages))

Ages: [22 35 41 28 53 60]
Shape: (6,)
Dimensions: 1
Data type: int64
Years until retirement: [43 30 24 37 12  5]
Average age: 39.833333333333336


## Task 2: Matrices

In [3]:
sales = np.array([[120, 135, 150],
                  [ 80,  95, 110],
                  [200, 180, 210],
                  [ 60,  75,  90]])
print(sales)
print("Shape:", sales.shape)
print("Total elements:", sales.size)

zero_matrix = np.zeros(sales.shape)
print("\nZero matrix:\n", zero_matrix)

# Replace second row using indexing
zero_matrix[1] = [10, 20, 30]
print("\nAfter replacing second row:\n", zero_matrix)

[[120 135 150]
 [ 80  95 110]
 [200 180 210]
 [ 60  75  90]]
Shape: (4, 3)
Total elements: 12

Zero matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

After replacing second row:
 [[ 0.  0.  0.]
 [10. 20. 30.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


## Task 3: Addition & Subtraction

In [4]:
term1 = np.array([[70, 65, 80],
                  [55, 60, 70],
                  [90, 85, 75]])
term2 = np.array([[75, 70, 85],
                  [65, 72, 78],
                  [88, 90, 80]])

total_marks = term1 + term2
print("Total marks (Term1 + Term2):\n", total_marks)

improvement = term2 - term1
print("\nImprovement (Term2 - Term1):\n", improvement)

# Total improvement per student (sum across subjects, axis=1)
total_improvement = improvement.sum(axis=1)
print("\nTotal improvement per student:", total_improvement)

best_student = np.argmax(total_improvement)
print(f"Student {best_student + 1} had the highest total improvement: {total_improvement[best_student]}")

Total marks (Term1 + Term2):
 [[145 135 165]
 [120 132 148]
 [178 175 155]]

Improvement (Term2 - Term1):
 [[ 5  5  5]
 [10 12  8]
 [-2  5  5]]

Total improvement per student: [15 30  8]
Student 2 had the highest total improvement: 30


## Task 4: Dot Product

In [5]:
prices = np.array([50, 120, 30, 200])
quantities = np.array([2, 1, 5, 3])

total_bill = np.dot(prices, quantities)
print("Total bill:", total_bill)

# 2 customers x 4 items
customers_qty = np.array([[2, 1, 5, 3],
                          [1, 0, 2, 4]])

# (2x4) . (4,) -> (2,) : one bill per customer
bills = np.dot(customers_qty, prices)
print("Bills for both customers:", bills)

# Why shapes must match:
# The dot product multiplies matching elements and sums them, so the inner dimensions
# must be equal. For (2x4) . (4,), the 4 columns (items) of the quantity matrix line up
# with the 4 prices. Each row (customer) is paired item-by-item with the price vector.
# If the sizes differed (e.g. 3 prices vs 4 quantities), some elements would have no
# partner, and NumPy raises a ValueError.

Total bill: 970
Bills for both customers: [970 910]


## Task 5: Reshaping

In [6]:
hours = np.array([2, 3, 1, 4, 5, 2, 3, 4, 6, 1, 2, 3])
print("Original:", hours, hours.shape)

# 4 rows x 3 columns (4 weeks of a 3-day study plan)
reshaped_4x3 = hours.reshape(4, 3)
print("\n4x3:\n", reshaped_4x3)

# A different valid shape
reshaped_2x6 = hours.reshape(2, 6)
print("\n2x6:\n", reshaped_2x6)

# Invalid reshape
try:
    hours.reshape(5, 3)
except ValueError as e:
    print("\nError:", e)

# Error message:
# ValueError: cannot reshape array of size 12 into shape (5,3)

Original: [2 3 1 4 5 2 3 4 6 1 2 3] (12,)

4x3:
 [[2 3 1]
 [4 5 2]
 [3 4 6]
 [1 2 3]]

2x6:
 [[2 3 1 4 5 2]
 [3 4 6 1 2 3]]

Error: cannot reshape array of size 12 into shape (5,3)


## Task 6: Indexing

In [7]:
np.random.seed(1)
matrix = np.random.randint(1, 51, size=(5, 5))
print(matrix)

print("\nElement at 3rd row, 4th column:", matrix[2, 3])

print("Last row:", matrix[-1])
print("Last column:", matrix[:, -1])

matrix[0, 0] = 999
print("\nUpdated matrix:\n", matrix)

[[38 44 13  9 10]
 [12  6 16  1 17]
 [ 2 13  8 46  7]
 [26 21 38 19 21]
 [12 43 29 30 15]]

Element at 3rd row, 4th column: 46
Last row: [12 43 29 30 15]
Last column: [10 17  7 21 15]

Updated matrix:
 [[999  44  13   9  10]
 [ 12   6  16   1  17]
 [  2  13   8  46   7]
 [ 26  21  38  19  21]
 [ 12  43  29  30  15]]


## Task 7: Slicing

In [8]:
m = np.arange(1, 37).reshape(6, 6)
print(m)

print("\nTop-left 3x3:\n", m[:3, :3])

print("\nEvery alternate row and column:\n", m[::2, ::2])

print("\nLast 2 rows and last 2 columns:\n", m[-2:, -2:])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Top-left 3x3:
 [[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]

Every alternate row and column:
 [[ 1  3  5]
 [13 15 17]
 [25 27 29]]

Last 2 rows and last 2 columns:
 [[29 30]
 [35 36]]


## Task 8: Random Matrices

In [9]:
np.random.seed(42)

# 3x3 random decimals between 0 and 1
rand_decimals = np.random.rand(3, 3)
print("Random decimals:\n", rand_decimals)

# 3x3 random integers between 10 and 100 (upper bound is exclusive)
rand_ints = np.random.randint(10, 101, size=(3, 3))
print("\nRandom integers:\n", rand_ints)

# 4x4 standard normal
rand_normal = np.random.randn(4, 4)
print("\nStandard normal:\n", rand_normal)

Random decimals:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]

Random integers:
 [[33 12 31]
 [62 11 97]
 [39 47 11]]

Standard normal:
 [[-0.46341769 -0.46572975  0.24196227 -1.91328024]
 [-1.72491783 -0.56228753 -1.01283112  0.31424733]
 [-0.90802408 -1.4123037   1.46564877 -0.2257763 ]
 [ 0.0675282  -1.42474819 -0.54438272  0.11092259]]


In [10]:
# Run part 1 twice using the same seed
np.random.seed(42)
run1 = np.random.rand(3, 3)

np.random.seed(42)
run2 = np.random.rand(3, 3)

print("Run 1:\n", run1)
print("Run 2:\n", run2)
print("Identical:", np.array_equal(run1, run2))

# Why identical: random numbers from NumPy are pseudo-random. They come from a
# deterministic algorithm whose starting state is set by the seed. The same seed gives
# the same starting state, hence the same sequence of numbers every time.
# (If the seed were NOT reset between the two calls, the generator would continue
# from where it left off and the second output would be different.)

Run 1:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
Run 2:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
Identical: True


## Task 9: Transpose

In [11]:
scores = np.array([[80, 85, 90, 78, 88],
                   [70, 75, 72, 80, 77],
                   [95, 92, 89, 94, 96]])
print("Original shape:", scores.shape)

scores_T = scores.T
print("Transposed shape:", scores_T.shape)
print(scores_T)

# Transposing twice returns the original
print("\nTranspose twice equals original:", np.array_equal(scores_T.T, scores))

Original shape: (3, 5)
Transposed shape: (5, 3)
[[80 70 95]
 [85 75 92]
 [90 72 89]
 [78 80 94]
 [88 77 96]]

Transpose twice equals original: True


In [12]:
A = np.array([[1, 2],
              [3, 4],
              [5, 6],
              [7, 8]])        # 4x2
B = np.array([[1, 0],
              [2, 1],
              [0, 3]])        # 3x2

# A (4x2) . B (3x2) is not possible: inner dimensions 2 and 3 do not match.
# Transposing B gives 2x3, so (4x2) . (2x3) works and gives 4x3.
result = np.dot(A, B.T)
print("Result shape:", result.shape)
print(result)

Result shape: (4, 3)
[[ 1  4  6]
 [ 3 10 12]
 [ 5 16 18]
 [ 7 22 24]]
